# Generated by Django 6.0.1 on 2026-01-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_productoservicio_clave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='referencia',
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='folio',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
