# Generated by Django 6.0.1 on 2026-01-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_presupuesto_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='folio',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
