# Generated by Django 6.0.1 on 2026-01-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_presupuesto_fecha_alter_presupuesto_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepresupuesto',
            name='unidad',
            field=models.CharField(default='PZA', max_length=20),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='cliente_ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='cliente_cp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='cliente_direccion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='proyecto',
            field=models.CharField(default='Proyecto...', max_length=200),
        ),
    ]
